//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizadorCat.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrganizadorCat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OrganizadorCat.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DataGrid.
        /// </summary>
        public static string DataGridPageTitle {
            get {
                return ResourceManager.GetString("DataGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a using MongoDB.Bson;
        ///using System.Globalization;
        ///using System.Windows.Data;
        ///using System;
        ///
        ///namespace OrganizadorCat.Converters
        ///{
        ///    public class IdToStringConverter : IValueConverter
        ///    {
        ///        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        ///        {
        ///            if (value is ObjectId objectId)
        ///            {
        ///                return objectId.ToString();
        ///            }
        ///            else
        ///            {
        ///                return &quot;&quot;;
        ///            }
        ///       [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string IdToStringConverter {
            get {
                return ResourceManager.GetString("IdToStringConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings page placeholder text.  Your app description goes here..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MaterialDarkBlue.
        /// </summary>
        public static string SettingsPageRadioButtonMaterialDarkBlueTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonMaterialDarkBlueTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MaterialDark.
        /// </summary>
        public static string SettingsPageRadioButtonMaterialDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonMaterialDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MaterialLightBlue.
        /// </summary>
        public static string SettingsPageRadioButtonMaterialLightBlueTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonMaterialLightBlueTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MaterialLight.
        /// </summary>
        public static string SettingsPageRadioButtonMaterialLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonMaterialLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Office2019Black.
        /// </summary>
        public static string SettingsPageRadioButtonOffice2019BlackTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonOffice2019BlackTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Office2019Colorful.
        /// </summary>
        public static string SettingsPageRadioButtonOffice2019ColorfulTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonOffice2019ColorfulTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Office2019DarkGray.
        /// </summary>
        public static string SettingsPageRadioButtonOffice2019DarkGrayTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonOffice2019DarkGrayTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Office2019HighContrast.
        /// </summary>
        public static string SettingsPageRadioButtonOffice2019HighContrastTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonOffice2019HighContrastTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Office2019White.
        /// </summary>
        public static string SettingsPageRadioButtonOffice2019WhiteTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonOffice2019WhiteTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Windows11Dark.
        /// </summary>
        public static string SettingsPageRadioButtonWindows11DarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindows11DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Windows11Light.
        /// </summary>
        public static string SettingsPageRadioButtonWindows11LightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindows11LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AutoComplete.
        /// </summary>
        public static string ShellAutoCompletePage {
            get {
                return ResourceManager.GetString("ShellAutoCompletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BusyIndicator.
        /// </summary>
        public static string ShellBusyIndicatorPage {
            get {
                return ResourceManager.GetString("ShellBusyIndicatorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carousel.
        /// </summary>
        public static string ShellCarouselPage {
            get {
                return ResourceManager.GetString("ShellCarouselPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Charts.
        /// </summary>
        public static string ShellChartsPage {
            get {
                return ResourceManager.GetString("ShellChartsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DataGrid.
        /// </summary>
        public static string ShellDataGridPage {
            get {
                return ResourceManager.GetString("ShellDataGridPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GridControl.
        /// </summary>
        public static string ShellGridControlPage {
            get {
                return ResourceManager.GetString("ShellGridControlPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open or close navigation.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PropertyGrid.
        /// </summary>
        public static string ShellPropertyGridPage {
            get {
                return ResourceManager.GetString("ShellPropertyGridPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
    }
}
